projectNEWM/newm-server

.github/workflows/klint.yml
.github/workflows/test-pull-request.yml
.github/workflows/test.yml
Dockerfile
build.gradle.kts
docker-compose.yml
newm-server-common/build.gradle.kts
newm-server-mobile/build.gradle.kts
newm-server-portal/build.gradle.kts
newm-server/build.gradle.kts

Klint and test workflows

---

newm-server/src/main/kotlin/io/newm/server/ext/StringExt.kt
newm-server/src/main/kotlin/io/newm/server/features/user/repo/UserRepositoryImpl.kt
newm-server/src/test/kotlin/io/newm/server/ext/IsValidEmailTests.kt
newm-server/src/test/kotlin/io/newm/server/ext/IsValidPasswordTests.kt
newm-server/src/test/kotlin/io/newm/server/features/user/TestUsers.kt

Update server to force password rules with Unit Test
Thanks @wlara for heloing me get my env setup properly!

Update password validation to match web

---

.github/workflows/ktlint.yml
buildSrc/src/main/kotlin/Dependencies.kt
newm-chain-grpc/build.gradle.kts

Bump dependencies including Kogmios to get the auto-reconnect functionality.

Auto reconnect to kogmios

---

newm-server/src/main/kotlin/io/newm/server/auth/AuthenticationRoutes.kt
newm-server/src/main/kotlin/io/newm/server/auth/oauth/OAuthType.kt
newm-server/src/main/kotlin/io/newm/server/auth/oauth/repo/OAuthRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/idenfy/repo/IdenfyRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/user/UserKoinModule.kt
newm-server/src/main/kotlin/io/newm/server/features/user/oauth/providers/AppleUserProvider.kt
newm-server/src/main/kotlin/io/newm/server/features/user/repo/UserRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/ktx/SecureApplicationEnvironmentExt.kt
newm-server/src/main/resources/application.conf

We can only test this after merging and deploying to garage.

CU-#86695c5pu | Sign in with Apple

---

newm-chain-grpc/src/main/proto/newm_chain.proto
newm-chain-util/src/main/kotlin/io/newm/chain/util/CardanoKtx.kt
newm-chain-util/src/main/kotlin/io/newm/chain/util/Sha3.kt
newm-chain/src/main/kotlin/io/newm/chain/grpc/NewmChainService.kt
newm-server/src/main/kotlin/io/newm/server/config/repo/ConfigRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/cardano/model/Key.kt
newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/minting/MintingMessageReceiver.kt
newm-server/src/main/kotlin/io/newm/server/features/minting/repo/MintingRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/minting/repo/MintingRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/ktx/KeyExt.kt
newm-server/src/main/kotlin/io/newm/server/ktx/StringExt.kt
newm-server/src/test/kotlin/io/newm/server/BaseApplicationTests.kt
newm-server/src/test/kotlin/io/newm/server/features/minting/repo/MintingRepositoryTest.kt
newm-tx-builder/src/main/kotlin/io/newm/txbuilder/TransactionBuilder.kt
newm-tx-builder/src/test/kotlin/io/newm/txbuildertest/TransactionBuilderTest.kt

We create the minting transaction in this PR. Some parts of the minting process are skipped and assumed to be successful. We will go back and fill in that code later. For example, once we have the distribution apis integrated.

CU-863g0zzvn: Build Minting Transaction

---

buildSrc/src/main/kotlin/Dependencies.kt
newm-server/build.gradle.kts
newm-server/src/integTest/kotlin/io/newm/server/AuthTest.kt
newm-server/src/integTest/kotlin/io/newm/server/HealthTest.kt
newm-server/src/integTest/kotlin/io/newm/server/StringExt.kt
newm-server/src/integTest/kotlin/io/newm/server/TestContext.kt
newm-server/src/integTest/kotlin/io/newm/server/UserTest.kt
newm-server/src/integTest/resources/garage.conf
newm-server/src/integTest/resources/studio.conf
newm-server/src/main/kotlin/io/newm/server/features/arweave/repo/ArweaveRepositoryImpl.kt

This PR creates a new integTest configuration and runs a series of sanity tests against the configured endpoint.
Usage:
```
export NEWM_EMAIL=you@email.com
export NEWM_PASSWORD=PassWordUsedToLoginToNewmPortal
./gradlew integTestGarage
```

Initial Integ Test setup

---

newm-server/src/integTest/kotlin/io/newm/server/SongsTest.kt
newm-server/src/integTest/kotlin/io/newm/server/TestContext.kt
newm-server/src/integTest/resources/garage.conf
newm-server/src/integTest/resources/studio.conf

This change adds integration/sanity tests to verify the behavior of the Songs API including uploading and transcoding media

Add integration tests for Songs API

---

buildSrc/src/main/kotlin/Dependencies.kt
newm-server/build.gradle.kts
newm-server/src/main/kotlin/io/newm/server/Application.kt
newm-server/src/main/kotlin/io/newm/server/aws/cloudfront/CloudfrontAudioStreamData.kt
newm-server/src/main/kotlin/io/newm/server/forwarder/ForwarderInstall.kt
newm-server/src/test/kotlin/io/newm/server/features/song/SongRoutesTests.kt

Including the Xforwarder to pass the Secure cookie check.  Tested locally with nginx proxy and confirmed working

Use secure cookies

---

newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepository.kt
newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepositoryImpl.kt
newm-chain-grpc/src/main/proto/newm_chain.proto
newm-chain/src/main/kotlin/io/newm/chain/grpc/NewmChainService.kt
newm-server/src/integTest/kotlin/io/newm/server/SongsTest.kt
newm-server/src/test/kotlin/io/newm/server/grpc/GrpcTests.kt

We need to know who is holding stream tokens when it comes time to pay out royalties.

CU-863h4germ: Snapshot tokens in newm-chain

---

newm-chain-db/src/main/kotlin/io/newm/chain/database/entity/LedgerUtxoHistory.kt
newm-chain-db/src/main/kotlin/io/newm/chain/database/migration/V11__CreateLedgerUtxoHistory.kt
newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepository.kt
newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepositoryImpl.kt
newm-chain-db/src/main/kotlin/io/newm/chain/database/table/LedgerUtxosHistoryTable.kt
newm-chain-db/src/main/kotlin/io/newm/chain/database/table/LedgerUtxosTable.kt
newm-chain-db/src/main/kotlin/io/newm/chain/model/CreatedUtxo.kt
newm-chain-db/src/main/kotlin/io/newm/chain/util/DbKtx.kt
newm-chain-util/src/main/kotlin/io/newm/chain/util/CardanoKtx.kt
newm-chain/src/main/kotlin/io/newm/chain/cardano/address/Address.kt
newm-chain/src/main/kotlin/io/newm/chain/cardano/address/AddressCredential.kt
newm-chain/src/main/kotlin/io/newm/chain/cardano/address/BIP32PublicKey.kt
newm-chain/src/main/kotlin/io/newm/chain/cardano/address/curve25519/Fe.kt
newm-chain/src/main/kotlin/io/newm/chain/cardano/address/curve25519/Ge.kt
newm-chain/src/main/kotlin/io/newm/chain/cardano/address/curve25519/GeAffine.kt
newm-chain/src/main/kotlin/io/newm/chain/cardano/address/curve25519/GeCached.kt
newm-chain/src/main/kotlin/io/newm/chain/cardano/address/curve25519/GeP1P1.kt
newm-chain/src/main/kotlin/io/newm/chain/cardano/address/curve25519/GePartial.kt
newm-chain/src/main/kotlin/io/newm/chain/cardano/address/curve25519/GePrecomp.kt
newm-chain/src/main/kotlin/io/newm/chain/cardano/address/curve25519/Helpers.kt
newm-chain/src/main/kotlin/io/newm/chain/cardano/address/curve25519/Scalar64.kt
newm-chain/src/main/kotlin/io/newm/chain/daemon/BlockDaemon.kt
newm-chain/src/test/kotlin/io/newm/chain/cardano/AddressDerivationTest.kt
newm-chain/src/test/kotlin/io/newm/chain/cardano/Cip68DatumTest.kt

Adds credentials so we can use newm-chain as a possible wallet backend.

Updates for newm-chain

---

newm-chain-util/src/main/kotlin/io/newm/chain/util/CardanoKtx.kt
newm-server/src/main/kotlin/io/newm/server/features/arweave/repo/ArweaveRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/song/model/SongBarcodeType.kt
newm-server/src/test/kotlin/io/newm/server/features/minting/ArweaveTest.kt

It appears we forgot to save the barcodes generated by eveara to our database.

Make sure we save generated EAN codes to db

---

newm-server/src/main/kotlin/io/newm/server/features/arweave/repo/ArweaveRepositoryImpl.kt
newm-server/src/test/kotlin/io/newm/server/json/TestJsonDecoding.kt

We changed to saving s3 urls in our database, but never updated the arweave code to handle them properly.

Generate pre-signed URLs for S3 url files that need to go to arweave

---

newm-server/src/main/kotlin/io/newm/server/features/distribution/DistributionRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/song/model/MintingStatus.kt

Also delete album/track on eveara if we're re-processing something that previously failed.

Fix release date for outlets

---

newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/ChainRepository.kt
newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/ChainRepositoryImpl.kt
newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepositoryImpl.kt
newm-chain/src/main/kotlin/io/newm/chain/daemon/BlockDaemon.kt
newm-server/src/main/kotlin/io/newm/server/features/arweave/repo/ArweaveRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt

newm-chain sync speed needed improvement.

Fix sync speed

---

newm-server/src/main/kotlin/io/newm/server/database/migration/V35__SongsUpdates.kt
newm-server/src/main/kotlin/io/newm/server/features/daemon/QuartzSchedulerDaemon.kt
newm-server/src/main/kotlin/io/newm/server/features/minting/MintingMessageReceiver.kt
newm-server/src/main/kotlin/io/newm/server/features/minting/model/MintInfo.kt
newm-server/src/main/kotlin/io/newm/server/features/minting/repo/MintingRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/minting/repo/MintingRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/song/database/SongEntity.kt
newm-server/src/main/kotlin/io/newm/server/features/song/database/SongTable.kt
newm-server/src/main/kotlin/io/newm/server/features/song/model/Song.kt

We need to save off this data so we know what token to snapshot for royalty payouts. Not sure how I forgot to save this info before.

Save Minting Info in the Songs table after successful mint

---

newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/distribution/DistributionRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/song/SongRoutes.kt
newm-server/src/main/kotlin/io/newm/server/features/song/model/MintPaymentResponse.kt
newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
newm-server/src/test/kotlin/io/newm/server/BaseApplicationTests.kt
newm-server/src/test/kotlin/io/newm/server/features/song/SongRoutesTests.kt
newm-server/src/test/kotlin/io/newm/server/grpc/GrpcTests.kt

Adding in the oracle feed.
Also fixing the label sent to DSP to ensure they set the copyright to the correct holder.

CU-86a0m3nw1: Send USD price of mint based on Charli3 Oracle Feed

---

newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepository.kt
newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepositoryImpl.kt
newm-chain-grpc/src/main/proto/newm_chain.proto
newm-chain/src/main/kotlin/io/newm/chain/cardano/MetadataKtx.kt
newm-chain/src/main/kotlin/io/newm/chain/grpc/NewmChainService.kt
newm-server/src/main/kotlin/io/newm/server/features/cardano/CardanoRoutes.kt
newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepositoryImpl.kt
newm-server/src/test/kotlin/io/newm/server/grpc/GrpcTests.kt

https://github.com/projectNEWM/newm-server/wiki/GetCardanoWalletNFTs

Add mobile wallet NFT API

---

buildSrc/src/main/kotlin/Dependencies.kt
newm-server/build.gradle.kts
newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/user/UserKoinModule.kt
newm-server/src/main/kotlin/io/newm/server/features/user/model/TokenInfo.kt
newm-server/src/main/kotlin/io/newm/server/features/user/repo/UserRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/user/verify/AppleMusicProfileUrlVerifier.kt
newm-server/src/main/kotlin/io/newm/server/features/user/verify/OutletProfileUrlVerifier.kt
newm-server/src/main/kotlin/io/newm/server/features/user/verify/SpotifyProfileUrlVerifier.kt
newm-server/src/main/kotlin/io/newm/server/security/KeyParser.kt
newm-server/src/main/resources/application.conf
newm-server/src/test/kotlin/io/newm/server/BaseApplicationTests.kt
newm-server/src/test/kotlin/io/newm/server/features/user/OutletProfileUrlVerifiersTest.kt
newm-server/src/test/resources/test-application.conf

Turn on validation for Apple/Spotify. Soundcloud will have to wait until we get an API key.

CU-86a1325cz, STUD-1: Validate Apple, Spotify, Soundcloud URLs

---

newm-server/src/main/kotlin/io/newm/server/features/minting/MintingMessageReceiver.kt

This just helps us with debugging to make sure the db matches whatever last came in from SQS.

Sync DB value with what is coming from SQS

---

newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt

This should "actually" fix it.

Attempted fix: Collection contains no element matching the predicate.

---

newm-server/src/main/kotlin/io/newm/server/features/minting/MintingMessageReceiver.kt
newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt

It appears when we're sending the next message to the queue, it's hanging until it's actually received. We are going to try to send in a separate coroutine so maybe it can start working.

Attempt to fix SQS receive hanging 3

---

newm-server/src/main/kotlin/io/newm/server/features/daemon/AwsSqsDaemon.kt

add logging to see why it's hanging.

Attempt to fix SQS receive hanging 6

---

newm-server/src/main/kotlin/io/newm/server/aws/AwsKoinModule.kt
newm-server/src/main/kotlin/io/newm/server/features/daemon/AwsSqsDaemon.kt
newm-server/src/main/kotlin/io/newm/server/ktx/SqsExt.kt

Putting things back the way they were and just setting a delivery attempt of 2 on the sqs queue. It should at least make things work until we find a better solution.

Attempt to fix SQS receive hanging 7

---

newm-server/src/main/kotlin/io/newm/server/features/minting/MintingMessageReceiver.kt
newm-server/src/main/kotlin/io/newm/server/features/song/SongRoutes.kt
newm-server/src/main/kotlin/io/newm/server/features/song/model/MintPaymentRequest.kt
newm-server/src/main/kotlin/io/newm/server/features/user/repo/UserRepositoryImpl.kt

Added a few extra tweaks in addition to the main PR topic.

CU-86a18h73m: Skip minting after distribution for already-minted songs

---

newm-server/src/main/kotlin/io/newm/server/features/song/model/MintPaymentResponse.kt
newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
newm-server/src/test/kotlin/io/newm/server/features/song/SongRepositoryTest.kt

need deeper breakdown of costs.

Give the frontend a complete cost breakdown for minting in ada and usd

---

newm-server/src/main/kotlin/io/newm/server/features/song/SongRoutes.kt

This is an extra server-side check to ensure we don't get through payment without setting a proper user walletAddress value. We should also fix this on the client side so when connecting wallet, we always save a non-null walletAddress by using `wallet.getChangeAddress()`

Set user.walletAddress during payment if not yet set

---

newm-server/src/main/kotlin/io/newm/server/features/cardano/CardanoRoutes.kt
newm-server/src/main/kotlin/io/newm/server/features/cardano/model/Key.kt

Need a way to get a key off the server so I can test metadata updates. This code will get commented out later.

Temporarily add getKeyByName API

---

newm-server/src/main/kotlin/io/newm/server/features/scheduler/EvearaReleaseStatusJob.kt

Forgot to save minting error to the db in this location.

Fix missed error message handling

---

newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/distribution/model/GetUserLabelResponse.kt

ERROR MintingMessageReceiver - Error while distributing!
2023-12-12T20:32:48.927000+00:00 i-018c586d73e192db3 Dec 12 20:32:48 ip-172-16-126-88 web: io.ktor.serialization.JsonConvertException: Illegal input: Field 'releases' is required for type with serial name 'io.newm.server.features.distribution.model.UserLabelData', but it was missing at path: $.data[0]

Fix npe for json parsing (maybe)

---

newm-server/build.gradle.kts

refactor to make test output more visible
Based on guidance from: https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_additional_test_types.html

refactor integTest tasks to be Gradle 9 compatible

---

newm-server/src/main/kotlin/io/newm/server/database/migration/V48__CreateSongErrorHistory.kt
newm-server/src/main/kotlin/io/newm/server/features/song/SongRoutes.kt
newm-server/src/main/kotlin/io/newm/server/features/song/database/SongErrorHistoryTable.kt
newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
newm-shared/src/main/kotlin/io/newm/shared/ktx/ByteReadChannelExt.kt

Docs -> https://github.com/projectNEWM/newm-server/wiki/ReprocessSong

STUD-177: Add API for resubmission of declined songs

---

newm-chain-grpc/src/main/proto/newm_chain.proto
newm-chain-util/src/main/kotlin/io/newm/chain/util/Constants.kt
newm-chain/src/main/kotlin/io/newm/chain/grpc/NewmChainService.kt
newm-chain/src/test/kotlin/io/newm/chain/cardano/SignDataVerificationTest.kt
newm-tx-builder/src/main/kotlin/io/newm/txbuilder/ktx/SigningKeyKtx.kt

This gives us signData() authentication for software (mnemonic) wallets.

MOBILE-184: Verify a signData login with user's stake address

---

buildSrc/src/main/kotlin/Dependencies.kt
gradle/wrapper/gradle-wrapper.properties
gradlew.bat
newm-chain/src/main/kotlin/io/newm/chain/daemon/BlockDaemon.kt
newm-server/build.gradle.kts
newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/earnings/EarningsKoinModule.kt
newm-server/src/main/kotlin/io/newm/server/features/earnings/EarningsRoutes.kt
newm-server/src/main/kotlin/io/newm/server/features/earnings/model/AddSongRoyaltyRequest.kt
newm-server/src/main/kotlin/io/newm/server/features/earnings/repo/EarningsRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/earnings/repo/EarningsRepositoryImpl.kt

This is an admin-only api designed to manually apply a certain number of newm tokens across all the stream token holder addresses for a given song.

STUD-85: Snapshot stream token holders for royalty splits

---

buildSrc/src/main/kotlin/Dependencies.kt
newm-server/build.gradle.kts
newm-server/src/main/kotlin/io/newm/server/auth/jwt/repo/JwtRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/auth/oauth/repo/OAuthRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/auth/twofactor/repo/TwoFactorAuthRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/cardano/parser/NFTSongParser.kt
newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/collaboration/repo/CollaborationRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/email/repo/EmailRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/idenfy/repo/IdenfyRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/playlist/repo/PlaylistRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/release/repo/OutletReleaseRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/song/AudioMessageReceiver.kt
newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/user/repo/UserRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/user/verify/AppleMusicProfileUrlVerifier.kt
newm-server/src/main/kotlin/io/newm/server/features/user/verify/SoundCloudProfileUrlVerifier.kt
newm-server/src/main/kotlin/io/newm/server/features/user/verify/SpotifyProfileUrlVerifier.kt
newm-server/src/main/kotlin/io/newm/server/features/walletconnection/repo/WalletConnectionRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/recaptcha/repo/RecaptchaRepositoryImpl.kt

Q1) Does this change include removing the file `LoggerExt.kt`? 
Q2) Are we replacing the logging lib in `projectNEWM/newm-server` ?

minor: STUD-169 replace LoggerExt.kt with a kotlin-logging library

---

newm-server/src/main/kotlin/io/newm/server/features/minting/MintingMessageReceiver.kt

It seems like error gets caught in catch statements and didn't get propagated all the way up, I'm following up on the latest update from Denny: 
- Looks like we’re almost where we need to be with this update:
✅ I was able to use the “[ForceError]” suffix when submitting my track in TestNet for minting and distribution.
✅ I also received the correct email notification that the artist should receive when a track moves into the “An error occurred” status.
:yellow_circle: The track in my Library doesn’t move to the “An error occurred” status within the UI

minor: STUD-214 update song status when force it to error

---

newm-server/src/main/kotlin/io/newm/server/features/user/repo/UserRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/user/repo/UserRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/recaptcha/RecaptchaKoinModule.kt
newm-server/src/main/kotlin/io/newm/server/recaptcha/repo/RecaptchaRepositoryImpl.kt

Will rebase and fix my formatting once the KTLint fix goes in.

Small fixes

---

newm-server/src/main/kotlin/io/newm/server/config/repo/ConfigRepository.kt
newm-server/src/main/kotlin/io/newm/server/database/migration/V62__ConfigUpdates.kt
newm-server/src/main/kotlin/io/newm/server/features/release/ReleaseKoinModule.kt
newm-server/src/main/kotlin/io/newm/server/features/release/model/SpotifyRequest.kt
newm-server/src/main/kotlin/io/newm/server/features/release/model/SpotifyResponse.kt
newm-server/src/main/kotlin/io/newm/server/features/release/model/SpotifyTrackItem.kt
newm-server/src/main/kotlin/io/newm/server/features/release/model/Tracks.kt
newm-server/src/main/kotlin/io/newm/server/features/release/repo/OutletReleaseRepository.kt
newm-server/src/main/kotlin/io/newm/server/features/release/repo/OutletReleaseRepositoryImpl.kt
newm-server/src/test/kotlin/io/newm/server/features/release/repo/OutletReleaseRepositoryTest.kt

Add API to automate addition of newly distributed and minted tracks to the NEWM Spotify playlist.

Add API to automate addition of newly distributed and minted tracks to the NEWM Spotify playlist.

---

newm-server/src/main/kotlin/io/newm/server/features/release/model/SpotifyRequest.kt
newm-server/src/main/kotlin/io/newm/server/features/release/repo/OutletReleaseRepositoryImpl.kt

`ERROR OutletReleaseStatusJob - Error in OutletReleaseStatusJob: org.quartz.JobDataMap@c730e949
kotlinx.serialization.SerializationException: Serializer for subclass 'OutletReleaseRepositoryImpl$$Lambda/0x00007f62308d3ce0' is not found in the polymorphic scope of 'Function0'.
Check if class with serial name 'OutletReleaseRepositoryImpl$$Lambda/0x00007f62308d3ce0' exists and serializer is registered in a corresponding SerializersModule.
To be registered automatically, class 'OutletReleaseRepositoryImpl$$Lambda/0x00007f62308d3ce0' has to be '@Serializable', and the base class 'Function0' has to be sealed and '@Serializable'.
#011at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:102)
#011at …

fix: STUD-291 Fix for add song to playlist not serializing properly

---

buildSrc/src/main/kotlin/Dependencies.kt
newm-server/build.gradle.kts
newm-server/src/main/kotlin/io/newm/server/Application.kt
newm-server/src/main/kotlin/io/newm/server/features/doc/DocumentationRoutes.kt
newm-server/src/main/kotlin/io/newm/server/features/minting/MintingMessageReceiver.kt
newm-server/src/main/resources/openapi/documentation.yaml

https://garage.newm.io/openapi
Will hold the docs after deployed.
Note: This is just a first pass of auto-generated documentation and some basic manual categorization I added. It might be incorrect in places. You can update the docs by editing the newm-server/src/main/resources/openapi/documentation.yaml file.

Add generated swagger docs

---

newm-server/src/main/kotlin/io/newm/server/features/marketplace/daemon/MarketplaceMonitorDaemon.kt

When we are monitoring addresses for the marketplace, the connection is torn down and rebuilt around once an hour. We should not log a scary error message in this scenario. Just re-establish the connection and move on with our life.

Disable scary log when we've simply disconnected due to max connection age

---

buildSrc/src/main/kotlin/Dependencies.kt
newm-chain-db/src/main/kotlin/io/newm/chain/util/DbKtx.kt
newm-server/build.gradle.kts
newm-server/src/main/kotlin/io/newm/server/aws/AwsKoinModule.kt
newm-server/src/main/kotlin/io/newm/server/aws/SqsMessageReceiver.kt
newm-server/src/main/kotlin/io/newm/server/aws/s3/AwsS3Utils.kt
newm-server/src/main/kotlin/io/newm/server/features/arweave/repo/ArweaveRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/daemon/AwsSqsDaemon.kt
newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/features/minting/MintingMessageReceiver.kt
newm-server/src/main/kotlin/io/newm/server/features/scheduler/ArweaveCheckAndFundJob.kt
newm-server/src/main/kotlin/io/newm/server/features/song/AudioMessageReceiver.kt
newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
newm-server/src/main/kotlin/io/newm/server/health/HealthCheckInstall.kt
newm-server/src/main/kotlin/io/newm/server/ktx/LambdaExt.kt
newm-server/src/main/kotlin/io/newm/server/ktx/SecureApplicationEnvironmentExt.kt
newm-server/src/main/kotlin/io/newm/server/ktx/SqsExt.kt
newm-server/src/test/kotlin/io/newm/server/BaseApplicationTests.kt
newm-server/src/test/kotlin/io/newm/server/features/arweave/repo/ArweaveRepositoryTest.kt
newm-server/src/test/kotlin/io/newm/server/features/minting/MintingMessageReceiverTest.kt

Should fix this warning in our code:
```
WARN  com.amazonaws.util.VersionInfoUtils - The AWS SDK for Java 1.x entered maintenance mode starting July 31, 2024 and will reach end of support on December 31, 2025. For more information, see https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-1-x-is-in-maintenance-mode-effective-july-31-2024/
```

STUD-309: Upgrade AWS SDK to v2

---

newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepositoryImpl.kt
newm-server/src/test/kotlin/io/newm/server/features/cardano/OracleParseTests.kt

Add more error handling to C3 to help us figure out why we are seeing an indexoutofboundsexception.

STUD-312: Use C3 NEWM/USD price feed on preprod

---

newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt

**Saif**> I think that this code might be causing the bug, can’t verify that without having access to DB (I ask James to grant my access to DB). 
**Andrew Westberg** >
It could be that we’re being too strict with the check. We’re expecting ALL collaborations to be accepted in one place, but only the collaborations with a non-zero royalty rate to be accepted in another. 
I think we should only require non-zero royalty collaborators to have accepted.

minor: STUD-217 should only require non-zero royalty collaborators to have accepted

---

newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepositoryImpl.kt

Need more info to debug where it's going wrong.

STUD-314: Add logging for oracle errors

---

newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt

Eveara will mark a user as disabled if they go 7 days after user creation without creating a subscription. We currently assign a subscription to all of our eveara user accounts at the point of distribution. When the NEWM user uploads music, but does not distribute right away, this results in a disabled account on the Eveara side. I've added code to ensure that the subscription is created right after user creation instead of waiting until they later choose to distribute their first song.
I've also cleaned up previous code that was checking for subscription in a song loop and moved it out. It wasn't hurting anything, but would have been a performance hit once we have album functionality and are releasing multiple songs at once.

STUD-313: Assign subscription at user creation

---

newm-server/src/main/kotlin/io/newm/server/Application.kt
newm-server/src/main/kotlin/io/newm/server/features/earnings/EarningsRoutes.kt
newm-server/src/main/kotlin/io/newm/server/features/earnings/model/GetEarningsResponse.kt
newm-server/src/test/kotlin/io/newm/server/BaseApplicationTests.kt
newm-server/src/test/kotlin/io/newm/server/TestApplication.kt
newm-server/src/test/kotlin/io/newm/server/features/earnings/EarningsRoutesTests.kt

Update the earning endpoint to return total amount for earnings that has been claimed.
**The test is failing due to unknown issue ! I can't figure out the root cause of it**

minor: STUD-326 return total amount for wallet address along with earnings 

---

newm-tx-builder/src/main/kotlin/io/newm/txbuilder/TransactionBuilder.kt
newm-tx-builder/src/main/kotlin/io/newm/txbuilder/ktx/PlutusLanguageKtx.kt

Fix the map creation for the plutusV3 languageviewmap

Fix scriptDataHash for plutusv3

---

build.gradle.kts
newm-tx-builder/src/main/kotlin/io/newm/txbuilder/TransactionBuilder.kt

Not sure what's going on here, but switching from the takeIf stuff to regular if/else solved the NPE. If you can see the bug, please let me know.

fix: tx_builder npe

---

newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt

`packet.readBytes()` does not `release()` the bytes.  `OutputStream.writePacket()` does internally call `release()`.

fix: Prevent OutOfMemoryException when uploading files

---

Procfile
build.gradle.kts

Need to make a change so that re-deploy can happen. Removing some old junk that we don't use anymore.

chore: remove heroku config

---

newm-chain/build.gradle.kts
newm-chain/src/main/kotlin/io/newm/chain/Application.kt
newm-server/build.gradle.kts
newm-server/src/main/kotlin/io/newm/server/Application.kt

Add build time so that we know what jar is actually running on the server.

chore: print build time on startup
