- .gitignore
- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- newm-server/build.gradle.kts
- newm-server/src/main/kotlin/io/newm/server/Application.kt
- newm-server/src/main/kotlin/io/newm/server/auth/twofactor/database/TwoFactorAuthEntity.kt
- newm-server/src/main/kotlin/io/newm/server/auth/twofactor/database/TwoFactorAuthTable.kt
- newm-server/src/main/kotlin/io/newm/server/database/DatabaseInit.kt
- newm-server/src/main/kotlin/io/newm/server/database/migration/V1__InitialCreation.kt
- newm-server/src/main/resources/application.conf
Flyway is not as easy to use as SchemaUtils.create..., but it does allow us to update our database over time adding columns, tables, and additional indexes as needed. 
The system scans the migrations folder for classes matching the pattern and plays back the migrations in order.  The results of migrations are stored in a `flyway_schema_history` table so they are only applied to the database once. Hashes of migrations are also stored in this table so once a migration is applied to the db, it cannot be changed and re-run.  Instead, you should create another migration file to fix what you broke.
> Add FlywayDB migrations

- newm-chain-db/src/main/kotlin/io/newm/chain/database/migration/V3__AlterLedgerUtxos.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepositoryImpl.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/database/table/LedgerUtxosTable.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/model/CreatedUtxo.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/model/Utxo.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/util/CardanoKtx.kt
- newm-server/src/main/kotlin/io/newm/server/content/ContentNegotiationInstall.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/SongEncodeMessageReceiver.kt
Datum values on UTxOs are used by the minting process. We will need to be able to query these values so that we can safely mint the next NFT in our sequence. We could keep track of this ourselves, but it's better to rely on the on-chain data.
> newm-chain: store utxo datum values

- newm-chain-db/src/main/kotlin/io/newm/chain/database/entity/ChainBlock.kt
- newm-chain/build.gradle.kts
- newm-chain/src/main/kotlin/io/newm/chain/daemon/BlockDaemon.kt
- newm-chain/src/main/kotlin/io/newm/chain/daemon/DaemonsKoinModule.kt
- newm-chain/src/main/kotlin/io/newm/chain/di/DependencyInjectionInstall.kt
- newm-chain/src/main/kotlin/io/newm/chain/grpc/NewmChainService.kt
- newm-chain/src/main/kotlin/io/newm/chain/ledger/LedgerKoinModule.kt
- newm-chain/src/main/kotlin/io/newm/chain/ledger/SubmittedTransactionCache.kt
- newm-chain/src/main/kotlin/io/newm/chain/ledger/SubmittedTransactionCacheImpl.kt
On the Cardano blockchain, sometimes a block gets replaced by another one. This is called a rollback. While it's possible to have rollbacks of many blocks, in practice, it's rare to see a rollback of more than 2 to 3 blocks. 
In the cardano-node's mempool, when a transaction is seen in a block, it is immediately removed from the mempool.
This causes a problem for us since our transaction could have been placed into a block and then a new block arrives rolling it back. Our transaction was in the original block, but it's now not in the new block. And now, our transaction is no longer in the mempool waiting to be put on the chain.
This code monitors for this condition and attempts to re-inflate the mempool with any of our transactions that have entered this weird state. By doing this, we …
> CU-863g0zzjf: Guaranteed Tx Delivery

- newm-server/src/main/kotlin/io/newm/server/auth/twofactor/repo/TwoFactorAuthRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/cardano/CardanoKoinModule.kt
- newm-server/src/main/kotlin/io/newm/server/features/idenfy/repo/IdenfyRepositoryImpl.kt
Several variables in environment are repeated in the secret manager but still referenced in the environment directly. This change updates the code that reads the environment to prefer reading the data from secret manager. These changes are required to adopt the new infrastructure that prefers secretmanager for config values.
> fix: update to use getSecureString for more config variables

- newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepository.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepositoryImpl.kt
- newm-chain/src/main/kotlin/io/newm/chain/grpc/NewmChainService.kt
- newm-tx-builder/src/main/kotlin/io/newm/txbuilder/TransactionBuilder.kt
We're not taking into account the bytes in the transaction that will eventually be filled by the signatures. If using the transactionBuilder to create an unsigned transaction, we need to add some dummy signatures so the eventual bytes calculation is correct.
> CU-863gy08ce: Fix fee calculation

- buildSrc/src/main/kotlin/Dependencies.kt
- newm-server/build.gradle.kts
- newm-server/src/main/kotlin/io/newm/server/aws/cloudfront/CloudfrontAudioStreamData.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/SongRoutes.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/model/AudioStreamResponse.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepository.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/security/KeyParser.kt
- newm-server/src/main/kotlin/io/newm/server/security/PrivateKeyReader.kt
- newm-server/src/main/resources/application.conf
- newm-server/src/test/kotlin/io/newm/server/aws/cloudfront/CloudfrontAudioStreamDataTest.kt
- newm-server/src/test/kotlin/io/newm/server/features/song/SongRoutesTests.kt
- newm-server/src/test/kotlin/io/newm/server/security/KeyParserTest.kt
- newm-server/src/test/kotlin/io/newm/server/security/PrivateKeyReaderTest.kt
- newm-server/src/test/resources/test-application.conf
This PR creates a new route `/v1/songs/${songId}/stream` that returns the url and meta data the player needs to stream the song.  Currently the meta data consists of the signed cookies needed to access the CloudFront CDN.
I chose the approach of making a separate call to obtain streaming metadata to give us maximum flexibility if we need to adjust the streaming requirements in the future.
This will require the client to perform an additional request before streaming a song, I'll work with @scandycuz  on how to implement that as a follow up task.
> add: new /stream route for generating secure signing data (cookies)

- newm-server/src/main/kotlin/io/newm/server/aws/cloudfront/CloudfrontAudioStreamData.kt
SameSite=Strict worked when developing locally, but its likely because I disabled certain security checks in my browser
> fix: trying SameSite=Lax to save cookies when streaming

- newm-server/src/main/kotlin/io/newm/server/features/daemon/DaemonsKoinModule.kt
Don't reference something injected inside the same module.
> Fix Circular dependency in Koin

- newm-server/src/main/kotlin/io/newm/server/aws/cloudfront/CloudfrontAudioStreamData.kt
- newm-server/src/test/kotlin/io/newm/server/aws/cloudfront/CloudfrontAudioStreamDataTest.kt
First step of enabling signed url params is to return them in the m3u8 url.
> feat:add auth url params to move away from cookies

- newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepository.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
If we ever have to re-process a song and some days have passed, ensure that the release date gets updated to still give the distributor enough time to review it. Otherwise, they just reject it a second time.
> CU-86a0vf8pv: Ensure release_date has enough time during distribution

- newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepositoryImpl.kt
We weren't diving deep enough into the Charli3 oracle datum structure. Needed to add one more list level.
```
$ cbor-diag --to diag <<< d8799fd87b9fa3001a0003bd6f011b0000018b438fe59b021b0000018b43c6d41bffff
121_0([_
123_0([_
{0: 245103_2, 1: 1697645585819_3, 2: 1697649185819_3},
]),
])
```
> Fix Charli3 Oracle feed

- newm-chain-db/src/main/kotlin/io/newm/chain/util/DbKtx.kt
- newm-chain/src/test/kotlin/io/newm/chain/cardano/Cip68DatumTest.kt
Some CIP68 NFTs store their datum value down in the witness set instead of inline with the tx body. Make sure we grab the datum value for these NFTs in that case.
> Fix some CIP68 NFT datum parsing

- newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
Saw some random errors:
```
POST https://staging.eveara.com/api/v2.1/oauth/gettoken: 500 URL Rewrite Module Error.. Text: "Error getting Eveara accessToken! - "
```
After reprocessing those songs, we got access token ok and they went through. When we are trying to get an access token, we should give it more than one shot since this is important.
> Add retry to eveara token fetch

- newm-server/src/main/kotlin/io/newm/server/features/minting/repo/MintingRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
- newm-server/src/test/kotlin/io/newm/server/features/song/SongRoutesTests.kt
Try switching from inline datum to offline datum values to reduce the cost since we don't hold the metadata in the active ledger.
> Decrease minting costs

- newm-server/src/main/kotlin/io/newm/server/features/daemon/AwsSqsDaemon.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
When two messages are sent to the queue very fast, the second one hangs in flight and is never received. Eventually, it lands in the DLQ
> Attempt to fix SQS receive hanging

- newm-server/src/main/kotlin/io/newm/server/features/daemon/AwsSqsDaemon.kt
Create a new Request object each time we loop so we clear the `receiveRequestAttemptId` that is automatically generated internally by AWS sqs library.
> Attempt to fix SQS receive hanging 2

- newm-server/src/main/kotlin/io/newm/server/features/daemon/AwsSqsDaemon.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
Since these calls are hanging, throw a timeout in there to see if we can figure out WTF is going on.
> Attempt to fix SQS receive hanging 4

- buildSrc/src/main/kotlin/Dependencies.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/database/entity/MonitoredAddressChain.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/database/migration/V13__CreateMonitoredAddressChain.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/ChainRepository.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/ChainRepositoryImpl.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepository.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepositoryImpl.kt
- newm-chain-db/src/main/kotlin/io/newm/chain/database/table/MonitoredAddressChainTable.kt
- newm-chain/src/main/kotlin/io/newm/chain/daemon/BlockDaemon.kt
- newm-chain/src/main/kotlin/io/newm/chain/daemon/DaemonsKoinModule.kt
- newm-chain/src/main/kotlin/io/newm/chain/daemon/MonitorAddressDaemon.kt
- newm-chain/src/main/kotlin/io/newm/chain/di/DependencyInjectionInstall.kt
- newm-shared/src/main/kotlin/io/newm/shared/daemon/Daemon.kt
This allows us to add a new address for monitoring without having to re-sync everything. We just sync the chain for the particular monitored address until it catches up to the blockchain tip. Then it starts receiving events from the normal BlockDaemon.
> Separate monitoring addresses into their own Daemons

- newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/distribution/model/GetUserLabelResponse.kt
- newm-server/src/main/kotlin/io/newm/server/features/distribution/model/UserLabelData.kt
Actual data is possible to not have the "releases" field inside the data object.
```
{
"message": "Currently showing 1 record(s)",
"success": true,
"total_records": 1,
"data": [
{
"label_id": 79308,
"is_active": 1,
"removable": true,
"name": "NEWM"
}
]
}
```
> Fix npe for json parsing

- newm-chain-db/src/main/kotlin/io/newm/chain/database/repository/LedgerRepositoryImpl.kt
Axo trade launch exposed how someone could put a null character into their metadata key and not just their metadata value. postgresql chokes on this so we escape it before it gets inserted.
> Ensure we can save null-containing metadata keys

- newm-chain-grpc/src/main/proto/newm_chain.proto
- newm-chain/src/main/kotlin/io/newm/chain/grpc/NewmChainService.kt
- newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepositoryImpl.kt
If something is wrong with the xpub key, we just get generic `io.grpc.StatusException: UNKNOWN` errors back on newm-server from newm-chain. This code captures errors and passes them back in an error_message field so we can throw the error on the newm-server side with something that makes sense.
> MOBILE-154: Pass xpub key errors back from newmchain

- newm-server/src/main/kotlin/io/newm/server/Application.kt
- newm-server/src/main/kotlin/io/newm/server/database/migration/V45__CreateEarnings.kt
- newm-server/src/main/kotlin/io/newm/server/di/DependencyInjectionInstall.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/EarningsKoinModule.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/EarningsRoutes.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/database/ClaimOrderEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/database/ClaimOrdersTable.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/database/EarningEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/database/EarningsTable.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/model/ClaimOrder.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/model/ClaimOrderStatus.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/model/Earning.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/repo/EarningsRepository.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/repo/EarningsRepositoryImpl.kt
I called the table "earnings" given that royalties are just one type of thing that can be claimed. Learn to earn rewards or referral rewards might also be included in a user's claimable earnings.
The earnings table holds are records of newmies that are allowed to be claimed by a given staking address. The claim_orders table holds a record that gets created when the user goes to claim. We create a payment address that is monitored for payment for a period of time before timing out. If payment is received, we will then create the transaction to send the user's earnings to them.
This first PR is just the creating of the database.
> STUD-97: Create tables for royalty claiming

- newm-server/src/main/kotlin/io/newm/server/database/migration/V47__CollaborationsUpdates.kt
- newm-server/src/main/kotlin/io/newm/server/features/collaboration/database/CollaborationEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/collaboration/database/CollaborationTable.kt
- newm-server/src/main/kotlin/io/newm/server/features/collaboration/model/Collaboration.kt
- newm-server/src/main/kotlin/io/newm/server/features/distribution/DistributionRepository.kt
- newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
In addition to the refactoring, the main logic change is removing the deleteAlbum() call and instead using updateAlbum(). So now, instead of deleting/re-creating the album record, we are trying to just update it.
> STUD-161: Ensure we only upload tracks to eveara once

- newm-server/src/main/kotlin/io/newm/server/features/minting/MintingMessageReceiver.kt
In the test environment, we will want to have some songs not be force distributed so we can manually decline several times and re-distribute several times for testing the unhappy paths.  We cannot use the distribution failure flag because the actual song is still sitting "in review" on the eveara side. This flag on a song removes any pretending on our side so we can test all the actual statuses on the eveara side.
> Bypass force_distribute for testing purposes

- build.gradle.kts
- newm-tx-builder/src/main/kotlin/io/newm/txbuilder/TransactionBuilder.kt
dummy collateral is 4 ada. Dummy fee was 3 ada. Total collateral is supposed to be fee * 1.5 which was 4.5 ada. Now setting the dummy fee to 2 ada, we're good to go.
> Fix: tx builder dummy fees

- newm-server/src/main/kotlin/io/newm/server/client/ClientKoinModule.kt
- newm-server/src/main/kotlin/io/newm/server/features/scheduler/EvearaReleaseStatusJob.kt
- newm-server/src/main/kotlin/io/newm/server/features/scheduler/OutletReleaseStatusJob.kt
There's no sense in a song falling out of our process with an error when it's just a temporary communication issue with eveara while we're checking status.
> STUD-187: Retry Eveara Status jobs on http communication errors

- build.gradle.kts
I needed to bump the version and deploy newm-tx-builder and other libs to maven since I had previously updated the underlying cbor library to fix a bug.
> bump version and deploy to maven central

- buildSrc/src/main/kotlin/Dependencies.kt
- newm-server/src/main/kotlin/io/newm/server/aws/AwsKoinModule.kt
- newm-server/src/main/kotlin/io/newm/server/database/migration/V53__CreateReleases.kt
- newm-server/src/main/kotlin/io/newm/server/features/arweave/ktx/SongExt.kt
- newm-server/src/main/kotlin/io/newm/server/features/arweave/repo/ArweaveRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/distribution/DistributionRepository.kt
- newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/marketplace/database/MarketplaceSaleEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/minting/repo/MintingRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/playlist/repo/PlaylistRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/scheduler/EvearaReleaseStatusJob.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/SongRoutes.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/database/ReleaseEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/database/ReleaseTable.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/database/SongEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/database/SongTable.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/model/Release.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/model/ReleaseBarcodeType.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/model/ReleaseType.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/model/Song.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepository.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
- newm-server/src/test/kotlin/io/newm/server/BaseApplicationTests.kt
- newm-server/src/test/kotlin/io/newm/server/features/arweave/ktx/SongExtTest.kt
- newm-server/src/test/kotlin/io/newm/server/features/cardano/CardanoRoutesTests.kt
- newm-server/src/test/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryTest.kt
- newm-server/src/test/kotlin/io/newm/server/features/marketplace/MarketplaceRoutesTests.kt
- newm-server/src/test/kotlin/io/newm/server/features/minting/repo/MintingRepositoryTest.kt
- newm-server/src/test/kotlin/io/newm/server/features/song/SongRoutesTests.kt
- newm-server/src/test/kotlin/io/newm/server/features/song/TestSongs.kt
This is a fairly extensive change that introduces the concept of a "release". A release can be a single, ep, album, or compilation. 
In this first iteration of the code, we are still assuming everything is a "single" so no front-end changes need to be made.
We're just moving some things up to the release level that used to be held in the songs table. 
It's not really possible to test everything until this code gets deployed to the garage environment. Then we'll have to do extensive testing to make sure we haven't broken anything.
Having this change on the server code should allow us to manually distribute one of our albums from the sample sale to the new system.
> STUD-220: Add some backend album support

- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- newm-server/src/main/kotlin/io/newm/server/features/collaboration/repo/CollaborationRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/email/repo/EmailRepositoryImpl.kt
- newm-tx-builder/src/main/kotlin/io/newm/txbuilder/ktx/PlutusDataKtx.kt
The fix is to pull in the new Cbor 0.2.2-NEWM version of the library. Other changes are code cleanup/tweaks.
> STUD-229: fix over-encoded integers in multi-item cbor

- newm-server/src/main/kotlin/io/newm/server/features/cardano/repo/CardanoRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/collaboration/database/CollaborationEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/collaboration/model/CollaborationFilters.kt
- newm-server/src/main/kotlin/io/newm/server/features/collaboration/model/CollaboratorFilters.kt
- newm-server/src/main/kotlin/io/newm/server/features/collaboration/repo/CollaborationRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/marketplace/database/MarketplaceSaleEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/marketplace/model/SaleFilters.kt
- newm-server/src/main/kotlin/io/newm/server/features/playlist/database/PlaylistEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/playlist/model/PlaylistFilters.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/database/ReleaseEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/database/SongEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/model/SongFilters.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/user/database/UserEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/user/model/UserFilters.kt
- newm-server/src/main/kotlin/io/newm/server/ktx/ApplicationCallExt.kt
- newm-server/src/main/kotlin/io/newm/server/model/FilterCriteria.kt
- newm-server/src/test/kotlin/io/newm/server/features/collaborations/CollaborationRoutesTests.kt
- newm-server/src/test/kotlin/io/newm/server/features/marketplace/MarketplaceRoutesTests.kt
- newm-server/src/test/kotlin/io/newm/server/features/minting/repo/MintingRepositoryTest.kt
- newm-server/src/test/kotlin/io/newm/server/features/playlist/PlaylistRoutesTests.kt
- newm-server/src/test/kotlin/io/newm/server/features/song/SongRoutesTests.kt
- newm-server/src/test/kotlin/io/newm/server/features/user/UserRoutesTests.kt
- newm-shared/src/main/kotlin/io/newm/shared/exposed/ExposedArrays.kt
Currently, we only need exclusion on the GetSales API filters,  but I added it to all API's for consistency. The way it works is that the caller simply adds a `-` prefix to every filter param value that should be used for exclusion or `+` for inclusion. For backward compatibility, if no prefix is found,  it defaults to inclusion.
> MRKT-72 | Support exclusion via API filter params

- newm-server/build.gradle.kts
- newm-server/src/main/kotlin/io/newm/server/features/cardano/parser/NFTSongParser.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
Context/Current State:
An artist had previously uploaded a track, but payment failed during the distribution and minting process. After the distribution errored out, the track was displayed in the Library with an Undistributed status; however, the artist was unable to edit details and/or delete the track. Afterward, each time the tried to re-upload/re-create a different track using the same audio file and title, a 409 error rendered, indicating a conflict with an existing song (because it had the same name as the one that couldn’t be deleted).
Acceptance Criteria/Desired State:
Any song that is in the “Undistributed” status in the Library, should be editable AND able to be deleted.
> Artists unable to delete Undistributed tracks in Library after failing to pay.

- newm-server/src/main/kotlin/io/newm/server/features/minting/ForceTrackToFailException.kt
- newm-server/src/main/kotlin/io/newm/server/features/minting/MintingMessageReceiver.kt
- newm-server/src/test/kotlin/io/newm/server/features/minting/MintingMessageReceiverTest.kt
**User Story:**
As a developer or product manager, I want to be able to force a track into the “An error occurred” status when I attempt to distribute a song in the TestNet environment so that I can test associated notifications and functionality when tracks are in this state.
> minor: STUD-214 Enable ability to force the "An error occurred" status

- newm-server/src/main/kotlin/io/newm/server/database/migration/V58__ReleasesUpdates.kt
- newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/database/ReleaseEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/database/ReleaseTable.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/model/Release.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
Take the eveara release id and base64 encode it. 
For the purposes of this ticket’s acceptance criteria: 
Add a new db column to the releases table to store this information.
Then calculate it and save it to the db.
> minor: STUD-239Add db column to capture release pre-save links page

- newm-server/src/main/kotlin/io/newm/server/features/earnings/daemon/MonitorClaimOrderJob.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/model/ClaimOrder.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/repo/EarningsRepositoryImpl.kt
Make sure we monitor the claimOrderId that is actually saved to the database.
> Fix claimOrderId

- newm-server/src/main/kotlin/io/newm/server/features/distribution/DistributionRepository.kt
- newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/features/user/UserRoutes.kt
- newm-server/src/test/kotlin/io/newm/server/features/user/UserRoutesTests.kt
In UserRoutes patch, we update the user in the userRepository database.
We also want to call both of these methods in EvearaDistributionRepositoryImpl after updating the user.
createDistributionUserIfNeeded(user)
createDistributionSubscription(user)
They might be private so you might have to add them to the DistributionRepository interface and make the methods public/override in the Impl class.
This ensures that if a user does something like update their name or their email address, the correct information is sync’d to eveara as well.
> minor: STUD-100 changes should be pushed to Eveara even outside of distribution and minting 

- newm-server/src/main/kotlin/io/newm/server/features/earnings/EarningsRoutes.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/database/ClaimOrderEntity.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/model/ClaimOrder.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/model/ClaimOrderRequest.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/model/GetEarningsResponse.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/repo/EarningsRepository.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/repo/EarningsRepositoryImpl.kt
- newm-server/src/main/resources/openapi/documentation.yaml
- newm-server/src/test/kotlin/io/newm/server/features/earnings/EarningsRoutesTests.kt
- newm-tx-builder/src/main/kotlin/io/newm/txbuilder/TransactionBuilder.kt
Please check the updated documentation once this is deployed. Both the GET and POST requests/responses for earnings have changed. 
The GET request includes an amountCborHex field that can be used to query the user's wallet for valid utxos to send in the POST request. The POST request requires the wallet being claimed for, a changeAddress, and the utxo list.
The response to the POST request now includes the cborHex of the transaction to sign to kick off the claiming process. Once this payment arrives, the user will be sent their tokens. 
As long as the claim order has not timed out, it's perfectly fine to call both GET and POST again if the user has closed their wallet, or declined to sign the transaction the first time. A new transaction will be built for them each time they call POST.
> STUD-325: Create Earnings fee transaction

- newm-chain-db/src/main/kotlin/io/newm/chain/util/DbKtx.kt
- newm-server/src/main/kotlin/io/newm/server/features/earnings/repo/EarningsRepositoryImpl.kt
- newm-server/src/main/kotlin/io/newm/server/ktx/InterProcessMutexExt.kt
- newm-server/src/main/resources/openapi/documentation.yaml
The way coroutines work, it's possible to resume on a different thread after a suspend function. This creates an extension function so we can use InterProcessMutex with coroutines to ensure we resume on the same physical JVM thread. This allows us to confidently release() the interprocess mutex since it will be acquired and released on the same physical JVM thread.
> Ensure proper threads for InterProcessMutex

- newm-server/src/main/kotlin/io/newm/server/cors/CorsInstall.kt
- newm-server/src/main/kotlin/io/newm/server/features/song/repo/SongRepositoryImpl.kt
I had thought POST was allowed by default, but maybe we updated a dependency that changed this.
> fix: Add POST to CORS

- newm-server/src/main/kotlin/io/newm/server/cors/CorsInstall.kt
allowMethod doesn't actually add it if it's considered one of the "Default" allowed by cors. However, when we look at the browser logs, POST is not being sent as one of the allowed methods so maybe there's a bug somewhere in the CORS implementation of ktor.
> fix: Add POST to CORS attempt 2

- newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
If the image is larger than 4000x4000, eveara fails with an error. We were trying to fix the error of the user uploading an image that was too small (under 100kb). I think it's better to just have those users upload more complex images instead of blocking people with larger images sizes.
> fix: STUD-352 - revert send uncompressed image to Eveara

- newm-server/src/main/kotlin/io/newm/server/Application.kt
print the args to the logs so we can ensure our jvm heap memory settings are being applied.
> chore: print cmdline args on startup

- .gitignore
- newm-server/src/main/kotlin/io/newm/server/features/earnings/repo/EarningsRepositoryImpl.kt
Current code fails with an exception if we don't find exactly 100m stream tokens on chain for a given song. This is usually because they are not in an address that is staked. If the tokens are not staked, any earnings should go to the NEWM foundation.
> fix: Unstaked stream token royalties go to NEWM Foundation

- newm-server/src/main/kotlin/io/newm/server/Application.kt
- newm-server/src/main/kotlin/io/newm/server/logging/InitializeLogging.kt
- newm-server/src/main/resources/logback.xml
Description
Our default logging system in logback.xml adds timestamps, threads, and class information about where each log line is coming from. However, we don’t know what AWS EC2 instance they are coming from.
Beanstalk combines all instance logs into one log file so it’s difficult to tell which server is printing the log. This is problematic when we’re dealing with things like Zookeeper leadership and you want to see which instance has the leadership.
> Fix logback.xml so that logs include the AWS server instance each line is coming from

- newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
We're seeing 
```
Server error(PATCH https://api.eveara.com/v2.1/outlets/100000780938/distribute: 400 . Text: "Error distributing release to outlets!: {"message":"Bad Request.","success":false,"errors":[{"message":"store_id 5180 is disabled.","code":8022}],"status_code":400}"
```
likely because the outlet data is out of date. Just fetch it each time we distribute instead of once daily.
> fix: Don't cache outlets

- buildSrc/src/main/kotlin/Dependencies.kt
- newm-server/build.gradle.kts
- newm-server/src/main/kotlin/io/newm/server/client/ClientKoinModule.kt
- newm-server/src/main/kotlin/io/newm/server/features/distribution/eveara/EvearaDistributionRepositoryImpl.kt
This happens on a good number of large songs we upload to eveara.
```
2025-05-12 17:14:15.613 [][DefaultDispatcher-worker-14] ERROR i.n.s.f.m.MintingMessageReceiver - Error while distributing!
java.io.EOFException: Failed to parse HTTP response: the server prematurely closed the connection
#011at io.ktor.client.engine.cio.UtilsKt$readResponse$2.invokeSuspend(utils.kt:174)
#011at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
#011at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
#011at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
#011at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
#011at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
#011at …
```
> fix: try to use okhttp for track uploads

- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/Versions.kt
- newm-chain/build.gradle.kts
The library has been renamed from sslcontext-kickstart to [ayza](https://github.com/Hakky54/ayza). The latest version is 10.0.0
Sorry for the inconvenience
> Bump and rename sslcontext-kicktart to ayza
